CREATE TABLE public.deck_card_association (
    deck_card_association int GENERATED BY DEFAULT AS IDENTITY,
	deck_id varchar(256) NOT NULL,
	card_id varchar(256) NOT NULL,
    CONSTRAINT deck_card_association_fk_deck FOREIGN KEY(deck_id) REFERENCES deck(deck_id),
    CONSTRAINT deck_card_association_fk_card FOREIGN KEY(card_id) REFERENCES card(card_id)
);